"""
22-Billion: Backtesting Engine
Historical strategy validation and optimization

FEATURES:
- Historical data backtesting
- Commission and slippage modeling
- Equity curve generation
- Performance metrics (Sharpe, max DD, win rate)
- Walk-forward analysis
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import json
from pathlib import Path


class BacktestEngine:
    """
    Professional backtesting engine for strategy validation
    
    Tests strategy on historical data to validate before live trading
    """
    
    def __init__(self, config, initial_balance=10000):
        self.config = config
        self.initial_balance = initial_balance
        
        # Cost parameters
        self.commission = 0.0004  # 0.04% (Binance futures maker fee)
        self.slippage = 0.0002  # 0.02% estimated slippage
        
        # Results storage
        self.trades = []
        self.equity_curve = []
        self.daily_returns = []
        
    def run_backtest(self, historical_data, strategy_signals):
        """
        Run backtest on historical data
        
        Args:
            historical_data: List of OHLCV candles
            strategy_signals: List of signals generated by strategy
            
        Returns:
            {
                'total_return': float,
                'win_rate': float,
                'profit_factor': float,
                'sharpe_ratio': float,
                'max_drawdown': float,
                'total_trades': int,
                'equity_curve': list
            }
        """
        print("🧪 Starting backtest...")
        
        balance = self.initial_balance
        equity = [balance]
        open_position = None
        
        # Simulate each signal
        for signal in strategy_signals:
            if signal['approved']:
                # Enter position
                if open_position is None:
                    entry_price = signal['entry_price']
                    stop_loss = signal['stop_loss']
                    take_profit = signal['take_profit']
                    signal_type = signal['signal_type']
                    
                    # Calculate position size (simple: risk 1% of balance)
                    risk_amount = balance * 0.01
                    stop_distance = abs(entry_price - stop_loss)
                    position_size = risk_amount / stop_distance
                    
                    # Apply commission
                    entry_cost = position_size * entry_price * self.commission
                    balance -= entry_cost
                    
                    open_position = {
                        'entry_price': entry_price,
                        'stop_loss': stop_loss,
                        'take_profit': take_profit,
                        'type': signal_type,
                        'size': position_size,
                        'entry_time': signal['timestamp']
                    }
                
                # Check for exit (simplified - assume hit TP or SL)
                # In real backtest, would check each candle
                else:
                    # Close position (assume TP hit for now)
                    exit_price = open_position['take_profit']
                    
                    if open_position['type'] == 'LONG':
                        pnl = (exit_price - open_position['entry_price']) * open_position['size']
                    else:
                        pnl = (open_position['entry_price'] - exit_price) * open_position['size']
                    
                    # Apply commission and slippage
                    exit_cost = open_position['size'] * exit_price * (self.commission + self.slippage)
                    pnl -= exit_cost
                    
                    balance += pnl
                    equity.append(balance)
                    
                    # Record trade
                    self.trades.append({
                        'entry_price': open_position['entry_price'],
                        'exit_price': exit_price,
                        'type': open_position['type'],
                        'pnl': pnl,
                        'balance': balance
                    })
                    
                    open_position = None
        
        # Calculate metrics
        results = self._calculate_metrics(equity)
        results['trades'] = self.trades
        results['equity_curve'] = equity
        
        print(f"✅ Backtest complete: {len(self.trades)} trades")
        
        return results
    
    def _calculate_metrics(self, equity_curve):
        """Calculate performance metrics"""
        if len(equity_curve) < 2:
            return {
                'total_return': 0,
                'total_return_pct': 0,
                'win_rate': 0,
                'profit_factor': 0,
                'sharpe_ratio': 0,
                'max_drawdown': 0,
                'max_drawdown_pct': 0,
                'total_trades': 0
            }
        
        # Total return
        total_return = equity_curve[-1] - equity_curve[0]
        total_return_pct = (total_return / equity_curve[0]) * 100
        
        # Win rate
        wins = sum(1 for t in self.trades if t['pnl'] > 0)
        total_trades = len(self.trades)
        win_rate = (wins / total_trades * 100) if total_trades > 0 else 0
        
        # Profit factor
        gross_profit = sum(t['pnl'] for t in self.trades if t['pnl'] > 0)
        gross_loss = abs(sum(t['pnl'] for t in self.trades if t['pnl'] < 0))
        profit_factor = (gross_profit / gross_loss) if gross_loss > 0 else 0
        
        # Sharpe ratio (simplified)
        returns = np.diff(equity_curve) / equity_curve[:-1]
        sharpe = (np.mean(returns) / np.std(returns)) * np.sqrt(252) if len(returns) > 0 and np.std(returns) > 0 else 0
        
        # Maximum drawdown
        peak = equity_curve[0]
        max_dd = 0
        
        for equity in equity_curve:
            if equity > peak:
                peak = equity
            dd = peak - equity
            if dd > max_dd:
                max_dd = dd
        
        max_dd_pct = (max_dd / peak * 100) if peak > 0 else 0
        
        return {
            'total_return': total_return,
            'total_return_pct': total_return_pct,
            'win_rate': win_rate,
            'profit_factor': profit_factor,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'max_drawdown_pct': max_dd_pct,
            'total_trades': total_trades,
            'winning_trades': wins,
            'losing_trades': total_trades - wins
        }
    
    def generate_report(self, results):
        """Generate human-readable backtest report"""
        report = f"""
╔══════════════════════════════════════════════════════════════════╗
║                    BACKTEST RESULTS                               ║
╚══════════════════════════════════════════════════════════════════╝

📊 Performance Summary:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Initial Balance:    ${self.initial_balance:,.2f}
Final Balance:      ${self.initial_balance + results['total_return']:,.2f}
Total Return:       ${results['total_return']:,.2f} ({results['total_return_pct']:+.2f}%)

📈 Trade Statistics:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Trades:       {results['total_trades']}
Winning Trades:     {results['winning_trades']}
Losing Trades:      {results['losing_trades']}
Win Rate:           {results['win_rate']:.2f}%
Profit Factor:      {results['profit_factor']:.2f}

📉 Risk Metrics:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Max Drawdown:       ${results['max_drawdown']:,.2f} ({results['max_drawdown_pct']:.2f}%)
Sharpe Ratio:       {results['sharpe_ratio']:.2f}

💡 Assessment:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
        
        # Assessment
        if results['win_rate'] >= 50 and results['profit_factor'] >= 1.5:
            report += "✅ GOOD: Strategy shows positive expectancy\n"
        elif results['win_rate'] >= 40 and results['profit_factor'] >= 1.2:
            report += "⚠️ ACCEPTABLE: Strategy is borderline profitable\n"
        else:
            report += "❌ POOR: Strategy needs improvement\n"
        
        if results['max_drawdown_pct'] <= 20:
            report += "✅ GOOD: Acceptable drawdown\n"
        else:
            report += "⚠️ WARNING: High drawdown - risky\n"
        
        report += "\n"
        report += "="*70
        
        return report
    
    def save_results(self, results, filename='backtest_results.json'):
        """Save backtest results to file"""
        filepath = Path('logs') / filename
        filepath.parent.mkdir(exist_ok=True)
        
        # Convert numpy types for JSON serialization
        serializable = {}
        for key, value in results.items():
            if isinstance(value, (np.integer, np.floating)):
                serializable[key] = float(value)
            elif isinstance(value, list):
                serializable[key] = [float(x) if isinstance(x, (np.integer, np.floating)) else x for x in value]
            else:
                serializable[key] = value
        
        try:
            with open(filepath, 'w') as f:
                json.dump(serializable, f, indent=2)
            print(f"💾 Backtest results saved to {filepath}")
        except Exception as e:
            print(f"⚠️ Could not save backtest results: {e}")
